# name: Deploy

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy using ssh
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USER_NAME }}
#           password: ${{ secrets.PASSWORD }}
#           script: |
#             cd /var/www/api.cashier.farhandev.cloud
#             git pull origin main
#             docker build -t superindo-cashier-api:latest .
#             docker rm -f superindo-cashier-api
#             docker run -d --name superindo-cashier-api -p 3004:8080 superindo-cashier-api:latest
