name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            env
            echo BROW
            whoami
            /home/farhan/.nvm/versions/node/v18.17.0/bin/pm2 -v
            cd /var/www/api.cashier.farhandev.cloud
            git pull origin main
            mvn clean install
            mv target/cashier-0.0.1-SNAPSHOT.jar .
            /home/farhan/.nvm/versions/node/v18.17.0/bin/pm2 delete cashier
            /home/farhan/.nvm/versions/node/v18.17.0/bin/pm2 start "java -jar cashier-0.0.1-SNAPSHOT.jar" --name cashier
